name: Staging

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Deploy to Render
      run: curl "$RENDER_DEPLOY_HOOK"
      env:
        RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}